server {
    listen 80;
    server_name fs.com fs.cn;
    charset utf-8;
    location / {
        alias ....../file-system/static/;
        index main.html;
    }
    location /html {
        alias /home/liuyao;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        # autoindex_format json;
        autoindex_format html;
        charset utf-8;
    }
    location /fs/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_set_header host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 2000m;
    }
}